<a href="https://colab.research.google.com/github/anamueller/IA/blob/main/Lista_Exerc%C3%ADcios_Pr%C3%A1ticos_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVC
from sklearn.svm import SVR
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [ ]:
#kfold q será utilizado no cross validation
kf = KFold(n_splits=5)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
vacinaja_class = pd.read_csv('/content/drive/MyDrive/CSV IA/geral_vacinaja_classificacao.csv')
vacinaja_regre = pd.read_csv('/content/drive/MyDrive/CSV IA/geral_vacinaja_regressao.csv')
vacinaja_geral = pd.read_csv('/content/drive/MyDrive/CSV IA/geral_vacinaja.csv')

#1)

In [ ]:
min_max_scaler = MinMaxScaler(feature_range=(0, 1))
escalado = vacinaja_geral

In [ ]:
escalado[["Populacao", "Area", "Dose 1", "Dose 2", "Doses Recebidas", "Classe (BOA=1 ou RUIM=0)"]] = min_max_scaler.fit_transform(escalado[["Populacao", "Area", "Dose 1", "Dose 2", "Doses Recebidas", "Classe (BOA=1 ou RUIM=0)"]])

In [ ]:
escalado.head()

Município  Populacao  ...  Doses Recebidas  Classe (BOA=1 ou RUIM=0)
0        ADAMANTINA   0.002781  ...         0.003810                       1.0
1            ADOLFO   0.000220  ...         0.000294                       1.0
2             AGUAÍ   0.002906  ...         0.002342                       1.0
3    ÁGUAS DA PRATA   0.000599  ...         0.000795                       1.0
4  ÁGUAS DE LINDÓIA   0.001458  ...         0.001618                       0.0

[5 rows x 7 columns]

In [ ]:
vacinaja_class[['col1','col2','col3','col4','col5']]= min_max_scaler.fit_transform(vacinaja_class[['col1','col2','col3','col4','col5']])
y = vacinaja_class['col6']
x = vacinaja_class.drop(['col6'], axis=1)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size= 0.3, random_state=29)

In [ ]:
x_train.shape

(451, 5)

In [ ]:
x_test.shape

(194, 5)

##KNN - Classificação

###Euclidiana

####1 Vizinho

In [ ]:
knn_eu_1 = KNeighborsClassifier(metric="euclidean", n_neighbors=1)

In [ ]:
 #usando o cross validation
 scores_knn_eu_1 = cross_val_score(knn_eu_1, x_train, y_train, cv=kf)
 media_knn_eu_1 = scores_knn_eu_1.mean()
 media_knn_eu_1

0.5875702075702075

In [ ]:
knn_eu_1.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [ ]:
y_pred1_eu_1 = knn_eu_1.predict(x_test)
y_pred1_eu_1

array([1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1])

In [ ]:
nota_KNN_eu_1 = accuracy_score(y_test, y_pred1_eu_1)

In [ ]:
nota_KNN_eu_1

0.5773195876288659

####3 Vizinhos

In [ ]:
knn_eu_3 = KNeighborsClassifier(metric="euclidean", n_neighbors=3)

In [ ]:
 #usando o cross validation
 scores_knn_eu_3 = cross_val_score(knn_eu_3, x_train, y_train, cv=kf)
 media_knn_eu_3 = scores_knn_eu_3.mean()
 media_knn_eu_3

0.6097680097680097

In [ ]:
knn_eu_3.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [ ]:
y_pred1_eu_3 = knn_eu_3.predict(x_test)
y_pred1_eu_3

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1])

In [ ]:
nota_KNN_eu_3 = accuracy_score(y_test, y_pred1_eu_3)

In [ ]:
nota_KNN_eu_3

0.5773195876288659

####5 Vizinhos

In [ ]:
knn_eu_5 = KNeighborsClassifier(metric="euclidean")

In [ ]:
 #usando o cross validation
 scores_knn_eu_5 = cross_val_score(knn_eu_5, x_train, y_train, cv=kf)
 media_knn_eu_5 = scores_knn_eu_5.mean()
 media_knn_eu_5

0.5920146520146521

In [ ]:
knn_eu_5.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
y_pred1_eu_5 = knn_eu_5.predict(x_test)
y_pred1_eu_5

array([0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1])

In [ ]:
nota_KNN_eu_5 = accuracy_score(y_test, y_pred1_eu_5)

In [ ]:
nota_KNN_eu_5

0.6030927835051546

###Manhattan

####5 Vizinhos

In [ ]:
knn_man = KNeighborsClassifier(metric="manhattan")

NameError: ignored

In [ ]:
 #usando o cross validation
 scores_knn_man = cross_val_score(knn_man, x_train, y_train, cv=kf)
 media_knn_man = scores_knn_man.mean()
 media_knn_man

In [ ]:
knn_man.fit(x_train, y_train)

In [ ]:
y_pred1_man = knn_man.predict(x_test)
y_pred1_man

In [ ]:
nota_KNN_man = accuracy_score(y_test, y_pred1_man)

In [ ]:
nota_KNN_man

####1 Vizinho

In [ ]:
knn_man_1 = KNeighborsClassifier(metric="manhattan", n_neighbors=1)

In [ ]:
 #usando o cross validation
 scores_knn_man_1 = cross_val_score(knn_man_1, x_train, y_train, cv=kf)
 media_knn_man_1 = scores_knn_man_1.mean()
 media_knn_man_1

0.5964102564102565

In [ ]:
knn_man_1.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='manhattan',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [ ]:
y_pred1_man_1 = knn_man_1.predict(x_test)
y_pred1_man_1

array([1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0])

In [ ]:
nota_KNN_man_1 = accuracy_score(y_test, y_pred1_man_1)

In [ ]:
nota_KNN_man_1

0.5773195876288659

####3 Vizinhos

In [ ]:
knn_man_3 = KNeighborsClassifier(metric="manhattan", n_neighbors=3)

In [ ]:
 #usando o cross validation
 scores_knn_man_3 = cross_val_score(knn_man_3, x_train, y_train, cv=kf)
 media_knn_man_3 = scores_knn_man_3.mean()
 media_knn_man_3

0.5986324786324786

In [ ]:
knn_man_3.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='manhattan',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [ ]:
y_pred1_man_3 = knn_man_3.predict(x_test)
y_pred1_man_3

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1])

In [ ]:
nota_KNN_man_3 = accuracy_score(y_test, y_pred1_man_3)

In [ ]:
nota_KNN_man_3

0.5979381443298969

##SVM - Classificação

### SMV - RBF

In [ ]:
svm = SVC()

In [ ]:
 #usando o cross validation
 scores_svm = cross_val_score(svm, x_train, y_train, cv=kf)
 media_svm = scores_svm.mean()
 media_svm

0.6010989010989011

In [ ]:
svm.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred2 = svm.predict(x_test)

In [ ]:
y_pred2

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
nota_SVM = accuracy_score(y_test, y_pred2)

In [ ]:
nota_SVM

0.6237113402061856

###SMV - Sigmoid

In [ ]:
svm_si = SVC(kernel='sigmoid')

In [ ]:
 #usando o cross validation
 scores_svm_si = cross_val_score(svm_si, x_train, y_train, cv=kf)
 media_svm_si = scores_svm_si.mean()
 media_svm_si

0.5433943833943834

In [ ]:
svm_si.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='sigmoid',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred2_svm_si = svm_si.predict(x_test)
y_pred2_svm_si

array([1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1])

In [ ]:
nota_SVM_si = accuracy_score(y_test, y_pred2)

In [ ]:
nota_SVM_si

0.6237113402061856

## Regressão

In [ ]:
vacinaja_regre[['col1','col2','col3','col5']]= min_max_scaler.fit_transform(vacinaja_regre[['col1','col2','col3','col5']])
y = vacinaja_regre['col4']
x = vacinaja_regre.drop(['col4'], axis=1)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size= 0.3, random_state=29)

##KNN - Regressão

###Eucliana

In [ ]:
knn_eu_re = KNeighborsRegressor(n_neighbors=5, metric="euclidean")

In [ ]:
 #usando o cross validation
 scores_knn_eu_re = cross_val_score(knn_eu_re, x_train, y_train, cv=kf)
 media_knn_eu_re = scores_knn_eu_re.mean()
 media_knn_eu_re

In [ ]:
knn_eu_re.fit(x_train, y_train)

In [ ]:
nota_knn_eu_re = knn_eu_re.score(x_test, y_test)

In [ ]:
nota_knn_eu_re

####3 Vizinhos

In [ ]:
knn_eu_re_3 = KNeighborsRegressor(n_neighbors=3, metric="euclidean")

In [ ]:
 #usando o cross validation
 scores_knn_eu_re_3 = cross_val_score(knn_eu_re_3, x_train, y_train, cv=kf)
 media_knn_eu_re_3 = scores_knn_eu_re_3.mean()
 media_knn_eu_re_3

In [ ]:
knn_eu_re_3.fit(x_train, y_train)

In [ ]:
nota_knn_eu_re_3 = knn_eu_re_3.score(x_test, y_test)

In [ ]:
nota_knn_eu_re_3

####1 Vizinho

In [ ]:
knn_eu_re_1 = KNeighborsRegressor(n_neighbors=1, metric="euclidean")

In [ ]:
 #usando o cross validation
 scores_knn_eu_re_1 = cross_val_score(knn_eu_re_1, x_train, y_train, cv=kf)
 media_knn_eu_re_1 = scores_knn_eu_re_1.mean()
 media_knn_eu_re_1

In [ ]:
knn_eu_re_1.fit(x_train, y_train)

In [ ]:
nota_knn_eu_re_1 = knn_eu_re_1.score(x_test, y_test)

In [ ]:
nota_knn_eu_re_1

###Manhattan

####5 Vizinhos

In [ ]:
knn_man_re = KNeighborsRegressor(n_neighbors=5, metric="manhattan")

In [ ]:
 #usando o cross validation
 scores_knn_man_re = cross_val_score(knn_man_re, x_train, y_train, cv=kf)
 media_knn_man_re = scores_knn_man_re.mean()
 media_knn_man_re

0.42694687623836486

In [ ]:
knn_man_re.fit(x_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='manhattan',
                    metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                    weights='uniform')

In [ ]:
nota_knn_man_re = knn_man_re.score(x_test, y_test)

In [ ]:
nota_knn_man_re

0.5985855237975677

####3 Vizinhos

In [ ]:
knn_man_re_3 = KNeighborsRegressor(n_neighbors=3, metric="manhattan")

In [ ]:
 #usando o cross validation
 scores_knn_man_re_3 = cross_val_score(knn_man_re_3, x_train, y_train, cv=kf)
 media_knn_man_re_3 = scores_knn_man_re_3.mean()
 media_knn_man_re_3

0.4699544516627111

In [ ]:
knn_man_re_3.fit(x_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='manhattan',
                    metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                    weights='uniform')

In [ ]:
nota_knn_man_re_3 = knn_man_re_3.score(x_test, y_test)

In [ ]:
nota_knn_man_re_3

0.6343495345130925

####1 Vizinho

In [ ]:
knn_man_re_1 = KNeighborsRegressor(n_neighbors=1, metric="manhattan")

In [ ]:
 #usando o cross validation
 scores_knn_man_re_1 = cross_val_score(knn_man_re_1, x_train, y_train, cv=kf)
 media_knn_man_re_1 = scores_knn_man_re_1.mean()
 media_knn_man_re_1

0.56534088057333

In [ ]:
knn_man_re_1.fit(x_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='manhattan',
                    metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                    weights='uniform')

In [ ]:
nota_knn_man_re_1 = knn_man_re_1.score(x_test, y_test)

In [ ]:
nota_knn_man_re_1

0.647434882258269

##SVM - Regressão

####RBF

In [ ]:
svm_re = SVR()

In [ ]:
 #usando o cross validation
 scores_svm_re = cross_val_score(svm_re, x_train, y_train, cv=kf)
 media_svm_re = scores_svm_re.mean()
 media_svm_re

-0.10954654324613973

In [ ]:
svm_re.fit(x_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [ ]:
nota_SVM_re = svm_re.score(x_test, y_test)

In [ ]:
nota_SVM_re

-0.09452772754176086

####SIGMOID

In [ ]:
svm_re_si = SVR(kernel='sigmoid')

In [ ]:
 #usando o cross validation
 scores_svm_re_si = cross_val_score(svm_re_si, x_train, y_train, cv=kf)
 media_svm_re_si = scores_svm_re_si.mean()
 media_svm_re_si

-0.10991937454096554

In [ ]:
svm_re_si.fit(x_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='sigmoid', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [ ]:
nota_SVM_re_si = svm_re_si.score(x_test, y_test)

In [ ]:
nota_SVM_re_si

-0.09458635473458821

#2)

In [ ]:
import plotly.graph_objects as go

In [ ]:
nota_class = []
numero_k = []
dist_algo = []
tipo_class = []

nota_class.append(nota_KNN_man)
dist_algo.append("manhattan")
numero_k.append(5)
tipo_class.append("Classificação")

nota_class.append(nota_KNN_man_3)
dist_algo.append("manhattan")
tipo_class.append("Classificação")
numero_k.append(3)

nota_class.append(nota_KNN_man_1)
dist_algo.append("manhattan")
tipo_class.append("Classificação")
numero_k.append(1)

nota_class.append(nota_KNN_eu_5)
dist_algo.append("euclidiana")
tipo_class.append("Classificação")
numero_k.append(5)

nota_class.append(nota_KNN_eu_1)
dist_algo.append("euclidiana")
tipo_class.append("Classificação")
numero_k.append(1)

nota_class.append(nota_KNN_eu_3)
dist_algo.append("euclidiana")
tipo_class.append("Classificação")
numero_k.append(3)

nota_class.append(nota_knn_eu_re)
dist_algo.append("euclidiana")
tipo_class.append("Regressão")
numero_k.append(5)

nota_class.append(nota_knn_eu_re_3)
dist_algo.append("euclidiana")
tipo_class.append("Regressão")
numero_k.append(3)

nota_class.append(nota_knn_eu_re_1)
dist_algo.append("euclidiana")
tipo_class.append("Regressão")
numero_k.append(1)

nota_class.append(nota_knn_man_re)
dist_algo.append("manhattan")
tipo_class.append("Regressão")
numero_k.append(5)

nota_class.append(nota_knn_man_re_3)
dist_algo.append("manhattan")
tipo_class.append("Regressão")
numero_k.append(3)

nota_class.append(nota_knn_man_re_1)
dist_algo.append("manhattan")
tipo_class.append("Regressão")
numero_k.append(1)

In [ ]:
valores = pd.DataFrame({'Tarefa':tipo_class, 'Distância':dist_algo, 'Nota':nota_class, 'N° K':numero_k})
valores

Tarefa   Distância      Nota  N° K
0   Classificação   manhattan  0.628866     5
1   Classificação   manhattan  0.597938     3
2   Classificação   manhattan  0.577320     1
3   Classificação  euclidiana  0.603093     5
4   Classificação  euclidiana  0.577320     1
5   Classificação  euclidiana  0.577320     3
6       Regressão  euclidiana  0.613464     5
7       Regressão  euclidiana  0.694523     3
8       Regressão  euclidiana  0.659651     1
9       Regressão   manhattan  0.598586     5
10      Regressão   manhattan  0.634350     3
11      Regressão   manhattan  0.647435     1

In [ ]:
classficacao = valores[valores['Tarefa'] == "Classificação"]
regressao = valores[valores['Tarefa'] == "Regressão"]

In [ ]:
euclidiana = classficacao[classficacao['Distância']== "euclidiana"]
manhattan = classficacao[classficacao['Distância']== "manhattan"]

In [ ]:
euclidiana_re = regressao[regressao['Distância']== "euclidiana"]
manhattan_re = regressao[regressao['Distância']== "manhattan"]

In [ ]:
fig3 = go.Figure(data=[
    go.Bar(name='Euclidiana', x=euclidiana['N° K'], y=euclidiana['Nota'], text=euclidiana['Nota'],
            textposition='auto',marker_color='rgb(144,224,239)', marker_line_color='rgb(0,150,199)',
                  marker_line_width=1.2, opacity=0.8),
    go.Bar(name='Manhattan', x=manhattan['N° K'], y=manhattan['Nota'], text=manhattan['Nota'],
            textposition='auto',marker_color='rgb(189,178,255)', marker_line_color='rgb(114,9,183)',
                  marker_line_width=1.2, opacity=0.8)
])
fig3.update_layout(barmode='group')
fig3.update_layout(title_text='Acurácia Tarefa de Classificação - Distância Euclidiana X Manhattan')
fig3.show()

In [ ]:
fig3 = go.Figure(data=[
    go.Bar(name='Euclidiana', x=euclidiana_re['N° K'], y=euclidiana_re['Nota'], text=euclidiana_re['Nota'],
            textposition='auto',marker_color='rgb(144,224,239)', marker_line_color='rgb(0,150,199)',
                  marker_line_width=1.2, opacity=0.8),
    go.Bar(name='Manhattan', x=manhattan_re['N° K'], y=manhattan_re['Nota'], text=manhattan_re['Nota'],
            textposition='auto',marker_color='rgb(189,178,255)', marker_line_color='rgb(114,9,183)',
                  marker_line_width=1.2, opacity=0.8)
])
fig3.update_layout(barmode='group')
fig3.update_layout(title_text='Score Tarefa de Regressão - Distância Euclidiana X Manhattan')
fig3.show()

  Podemos ver que para a tarefa de classificação, a distância "Manhattan", obteve uma acurácia maior. Já na tarefa de Regressão, a distância euclidiana se mostrou mais eficiente.

Quanto ao número de Vizinhos, na tarefa de classificação, o melhor número de vizinhos, entre os escolhidos, foi o 5. Para de regressão, 3.

#3)

In [ ]:
kernel = ['RBF', 'SIGMOID']

grafico = [go.Bar(x=kernel, y=[nota_SVM, nota_SVM_si], textposition='auto',marker_color='rgb(144,224,239)', marker_line_color='rgb(0,150,199)',
                  marker_line_width=1.2, opacity=0.8, text=[nota_SVM, nota_SVM_si])]
layout = layout = go.Layout(title="Acurácia Classficação SVM - RBF X Sigmoid")
fig = go.Figure(data=grafico, layout=layout)

fig.show()

In [ ]:
kernel = ['RBF', 'SIGMOID']

grafico = [go.Bar(x=kernel, y=[nota_SVM_re, nota_SVM_re_si], textposition='auto',marker_color='rgb(144,224,239)', marker_line_color='rgb(0,150,199)',
                  marker_line_width=1.2, opacity=0.8, text=[nota_SVM_re, nota_SVM_re_si])]
layout = layout = go.Layout(title="Score Regressão SVM - RBF X Sigmoid")
fig = go.Figure(data=grafico, layout=layout)

fig.show()

Para os dois paramêtros de Kernels testados, não houve muita alteração nos valores de Acurácia para a tarefa de classificação e Score, para a tarefa de Regressão. 

#4)

In [ ]:
parametros = {'C':[0.1,1,10,100], 'gamma':[1,0.1,0.01,0.001]}

##Classificação

In [ ]:
grid_Search = GridSearchCV(SVC(), parametros)

In [ ]:
grid_Search.fit(x_train, y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [1, 0.1, 0.01, 0.001]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
grid_Search.best_params_

{'C': 100, 'gamma': 1}

In [ ]:
grid_Search.best_score_

0.6342368742368742

##Regressão

In [ ]:
grid_Search_re = GridSearchCV(SVR(), parametros)

In [ ]:
grid_Search_re.fit(x_train,y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVR(C=1.0, cache_size=200, coef0=0.0, degree=3,
                           epsilon=0.1, gamma='scale', kernel='rbf',
                           max_iter=-1, shrinking=True, tol=0.001,
                           verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [1, 0.1, 0.01, 0.001]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
grid_Search_re.best_params_

{'C': 100, 'gamma': 1}

In [ ]:
grid_Search_re.best_score_

-0.1743078436905784

Para a tarefa de classificação, usar o gridSearch melhorou a acurácia do modelo, já para a tarefa de regressão, o Score diminuiu.